version: '3'

services:
    data_controller:
        container_name: ${CONTAINER_NAME}
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ${SERVER_PATH}:/app/
        ports:
            - "${CONTAINER_PORT}:80"
            - "12345:22"
        env_file:
            - .env
