version: '3'

services:
    data_controller:
        container_name: ${CONTAINER_NAME}
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ${DATA_PATH}:/data/
        ports:
            - "${CONTAINER_PORT}:80"
        env_file:
            - .env
